### ISSUE TITLE
Allow linking/delegating/appending docs of a rule to macro definition when kwarg is used

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/skydoc#115] opened 2018-10-26 11:11 UTC
Hi,  
We often have macros which add a few shims on top of existing rules and so use the `kwargs` pattern. We use it since the macros mostly add our own organizational conventions on top of community rules.
Alternatively we have a macro which constructs a few targets but one of them is primary and so the kwargs is passed to that.

The FR here is to allow us to annotate the macro and link to the rule so that we can reuse that documentation and not duplicate it.
Honestly I'd love this to be also relevant for code completion when it comes for the same reasons but not sure where to add such an issue (cc @laurentlb who'll probably have an answer)

**Comment by ittaiz** [comment] 2019-01-23 20:58
@c-parsons apparently I opened the issue already :)

**Comment by c-parsons** [comment] 2019-01-23 21:50
I knew this sounded familiar and that it had come from you...

Definitely on the radar. Thanks for bringing this up again.

**Comment by brandjon** [comment] 2019-04-10 20:14
Filed #182 as a general FR to support links. This would seem to be a structured-field special case of that.

**Comment by c-parsons** [comment] 2019-10-15 20:37
Closed as a psuedo-duplicate of https://github.com/bazelbuild/stardoc/issues/27. We'd need to address this concern for that issue.

**Closed by c-parsons** 2019-10-15 20:37 UTC
