### ISSUE TITLE
Add support for templating the output

### ISSUE THREAD

**Issue by sergiocampama** [bazelbuild/skydoc#144] opened 2019-01-17 14:52 UTC
Currently the output of the `stardoc`rule is a markdown file that contains the rules as `##` elements. It would be very useful to be able to set a template with an entry point for `stardoc` to inject the generated content, and make it easier to use the output of `stardoc` without further documentation setup.

**Comment by c-parsons** [comment] 2019-01-17 18:49
This is a duplicate of https://github.com/bazelbuild/skydoc/issues/120

**Closed by c-parsons** 2019-01-17 18:49 UTC
