### ISSUE TITLE
.bzl dependency not found, even though it's specified through a bzl_library dep

### ISSUE THREAD

**Issue by jin** [bazelbuild/skydoc#174] opened 2019-03-16 17:32 UTC
Maybe related? https://github.com/bazelbuild/skydoc/issues/137

Repro:

```
$ git clone https://github.com/bazelbuild/rules_jvm_external /tmp/r_j_e
$ cd /tmp/r_j_e
$ git checkout stardoc
$ bazel build :defs_doc

DEBUG: Rule 'io_bazel_skydoc' modified arguments {"shallow_since": "1552068165 -0500"}
DEBUG: Rule 'io_bazel_rules_sass' modified arguments {"shallow_since": "1542966119 +0100"}
DEBUG: Rule 'bazel_skylib' modified arguments {"shallow_since": "1549647446 +0100"}
INFO: Analysed target //:defs_doc (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/jin/Code/rules_jvm_external/BUILD:14:1: Generating Starlark doc for defs_doc failed (Exit 1) skydoc failed: error executing command bazel-out/host/bin/external/io_bazel/src/main/java/com/google/devtools/build/skydoc/skydoc '--input=//:defs.bzl' '--output=bazel-out/darwin-fastbuild/bin/defs_doc.md' '--symbols=maven_install' ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Exception in thread "main" java.lang.IllegalStateException: File defs.bzl imported '@rules_jvm_external//:coursier.bzl', yet external/rules_jvm_external/coursier.bzl was not found, even at roots [.].
	at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:434)
	at com.google.devtools.build.skydoc.SkydocMain.eval(SkydocMain.java:346)
	at com.google.devtools.build.skydoc.SkydocMain.main(SkydocMain.java:204)
Caused by: java.nio.file.NoSuchFileException: external/rules_jvm_external/coursier.bzl
	at com.google.devtools.build.skydoc.SkydocMain.getInputSource(SkydocMain.java:466)
	at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:418)
	at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:430)
	... 2 more
Target //:defs_doc failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.267s, Critical Path: 1.05s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

BUILD file:

```python
load("@io_bazel_skydoc//stardoc:stardoc.bzl", "stardoc")
load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

exports_files(["defs.bzl", "coursier.bzl"])

stardoc(
    name = "defs_doc",
    input = "defs.bzl",
    out = "defs_doc.md",
    deps = ["//:implementation"],
    symbol_names = ["maven_install"]
)

bzl_library(
    name = "implementation",
    srcs = [
        ":specs.bzl",
        ":defs.bzl",
        ":coursier.bzl",
        "//third_party/bazel_json/lib:json_parser.bzl"
    ],
)
```

`--experimental_remap_main_repo` didn't work (?). If I remove `@rules_jvm_external` from the load statements in `defs.bzl`, it works.

**Comment by c-parsons** [comment] 2019-03-18 20:12
So, the issue is that Stardoc sees, in `//:defs.bzl`:

```
load("@rules_jvm_external//:coursier.bzl")
```

and assumes that this file is present at `external/rules_jvm_external/coursier.bzl`. This is because it has no knowledge that the current workspace is `@rules_jvm_external`, and, if it were evaluating in any other workspace, that would be the correct location.

We'll thus need to modify Stardoc to make it take information about the current workspace name.

**Comment by c-parsons** [comment] 2019-03-19 21:17
This will be fixed by https://github.com/bazelbuild/bazel/commit/453c1e844eecff59afcbca01b4471e4182711c03

**Comment by jin** [comment] 2019-03-19 21:21
Thanks!

**Comment by c-parsons** [comment] 2019-03-19 21:28
Oops. I closed this prematurely. I need to implement a change in the stardoc rule in this repository, as well. Working on that now ;)

**Closed** 2019-03-19 21:55 UTC
